name: xml-compliance-checker
services:
- name: backend
  source_dir: /ai_compliance/Backend
  github:
    repo: your-github-username/xml_compliance_against_iso_rules_2
    branch: main
  run_command: gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 main:app
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 5000
  health_check:
    http_path: /api/health
  envs:
  - key: FLASK_ENV
    value: production
  - key: OPENAI_API_KEY
    value: YOUR_OPENAI_API_KEY_HERE
    type: SECRET
  - key: PYTHONUNBUFFERED
    value: "1"
  - key: PORT
    value: "5000"

static_sites:
- name: frontend
  source_dir: /ai_compliance/Frontend
  github:
    repo: your-github-username/xml_compliance_against_iso_rules_2
    branch: main
  build_command: npm ci && VITE_API_BASE_URL=${backend.PUBLIC_URL}/api npm run build
  output_dir: /dist
  routes:
  - path: /
